### PR TITLE
nicola's proposal prototype.

### PR DESCRIPTION
**Pull request by naighes**
Hello Luchino.
It's just my proposal. Take it as is and please feel no obligation to merge.
New stack looks (to me) fully async and it _should_ relies on Windows I/O completion ports.
Some tests are broken and should be reviewed as well.
@lsfera , @matteobaglini and @luigiberrettini in cc! :-)

### CODE REVIEW

**Comment by naighes** [comment]
#2f83b32 fixes the wrong compare exchange bug.

**Comment by naighes** [comment]
@lsfera - @luigiberrettini - @matteobaglini - @lucamilan 
Here I'm.
I've updated this PR so the client could offer some recovery capabilty.
As always, going yo be just a proposal.
Feel free to review/discard/whatever.

HTH.

PS. @matteobaglini (aka "Livorno") provided me a couple of very useful hints and latest changes are driven by those suggestions as well.

**Comment by naighes** [comment]
Ok guys.
This should be my last contribution.
Yeah, it could be further and widely improved, but I guess it's enough for now.
The only real change I introduced was uniform interface between static and instance API.
The instance one obviously requires heavy synchronization and it'll be a lot slower.
The instance one is by far the suggested approach, but as Luchino suggested we can provide both approaches.

@lsfera - @luigiberrettini - @matteobaglini - @lucamilan 

PS. As you merge this PR (if you really want) we can close it as well. I'll open a new one in case.
PPS. Any concern/suggestion is well accepted and encouraged.
PPPS. Should be tested like hell.

**Comment by lucamilan** [comment]
merge from nic

**Comment by luigiberrettini** [comment]
Sono riuscito a guardarci solo ora scusate.
Io sostituirei i vari tipi con un generico, in questo modo siamo aperti anche all'invio di stringhe e decimal e di tipi che implementino il toString (ora non mi vengono in mente casi ma potrei avere un dominio di valori ristretto e voler vedere quante occorrenze ho su un grafico)

**Comment by naighes** [comment]
Zizi, avevamo fatto così prima.
Graphite, però, supporta solo "numbers" e quindi abbiamo cambiato strada.

## 

N.

2016-05-06 15:16 GMT+02:00 Luigi Berrettini notifications@github.com:

> Sono riuscito a guardarci solo ora scusate.
> Io sostituirei i vari tipi con un generico, in questo modo siamo aperti
> anche all'invio di stringhe e decimal e di tipi che implementino il
> toString (ora non mi vengono in mente casi ma potrei avere un dominio di
> valori ristretto e voler vedere quante occorrenze ho su un grafico)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lucamilan/MiniMetrics/pull/1#issuecomment-217436677

## 

Nicola Baldi

Mob. +39 338 13.48.475
LinkedIn: http://www.linkedin.com/in/nicolabaldi
SlideShare: http://www.slideshare.net/Naighes
Twitter: @NicolaBaldi
Skype: nic.baldi1

**Pull request merged**
